### ISSUE TITLE
Wazzup first issue

### ISSUE THREAD

**Issue by TitaniumHocker** [michaelbukachi/flask-vuesfc#1]
This project looks very interesting. I wish you good luck in further development and support of the project. 

Flask sorely lacks such extensions that allow you to use JS frameworks as extensions. 

Also It seems to me better to rename the repository to `Flask-VueSFC` or something like this. And I didn't found `LICENSE` file in the repo.

**Comment by michaelbukachi** [comment]
Thanks the for feedback :smile:
